// Generated by CoffeeScript 1.6.3
buster.spec.expose();

describe('github', function() {
  return it('fetches the correct count', function(done) {
    var count;
    return count = new repocount({
      github: 'demo'
    }, function(res) {
      return done(buster.assert.equals(res.github.length, 1));
    });
  });
});
