// Generated by CoffeeScript 1.6.3
var Repocount;

Repocount = require('../repocount');

exports.github = function(test) {
  var count;
  return count = new Repocount({
    github: 'demo'
  }, function(res) {
    test.expect(res.length).to.equal(1);
    return test.done();
  });
};
